### PR TITLE
Pause Menu

### PR DESCRIPTION
**Pull request by Yunnity**
Pause Button on controller is the "start" button (the one on the right)
Restart button changed on controller to the north button

### CODE REVIEW

**Comment by crookedspider1** [comment]
We can probably change restart to the north button instead, share will be bound to do other stuff in some environments which isn't great.

**Comment by crookedspider1** [comment]
The "resume" button doesnt change size in the pause menu, but the quit button does. also they both have the unchanged version behind them which looks weird, we need a blank version of the page behind them. Also we might want an animation curve on that size increase/decrease to look something like this as a little bit more polish.
Screenshot 2024-10-31 at 3 47 29 PM

**Comment by Yunnity** [comment]
> The "resume" button doesnt change size in the pause menu, but the quit button does. also they both have the unchanged version behind them which looks weird, we need a blank version of the page behind them. Also we might want an animation curve on that size increase/decrease to look something like this as a little bit more polish. Screenshot 2024-10-31 at 3 47 29 PM

The resume and quit buttons both "change size" when they the selected/hovered buttons (?)
As for the animations/making it look smooth + blank menu, we can get those done in a future PR when we have the necessary assets I think

**Comment by dungwoong** [comment]
looks good to me

**Review by crookedspider1 — APPROVED** [review]

**Pull request merged**
